on: workflow_dispatch
name: TestServers-Deployment
jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
    # flag that determines if the test servers needs to be deployed to region#2
    # this helps in reusing this workflow for single and multiregion scenarios
      DEPLOY_MULTIREGION: false

    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
        
    - name: Run ARM deploy for Test Servers in region1-spoke1
      uses: azure/arm-deploy@v1
      if: ${{ env.DEPLOY_MULTIREGION == true }}
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_360 }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./02-BaseSetup-MultiRegion/Templates/TestServerTemplate.json
        parameters: ./02-BaseSetup-MultiRegion/Templates/TestServerParameters-region1-spoke1.json

    - name: Run ARM deploy for Test Servers in region1-spoke2
      uses: azure/arm-deploy@v1
      if: ${{ env.DEPLOY_MULTIREGION == true }}
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_360 }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./02-BaseSetup-MultiRegion/Templates/TestServerTemplate.json
        parameters: ./02-BaseSetup-MultiRegion/Templates/TestServerParameters-region1-spoke2.json

    - name: Run ARM deploy for Test Servers in region2-spoke1
      uses: azure/arm-deploy@v1     
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_360 }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./02-BaseSetup-MultiRegion/Templates/TestServerTemplate.json
        parameters: ./02-BaseSetup-MultiRegion/Templates/TestServerParameters-region2-spoke1.json

    - name: Run ARM deploy for Test Servers in region2-spoke2
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_360 }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./02-BaseSetup-MultiRegion/Templates/TestServerTemplate.json
        parameters: ./02-BaseSetup-MultiRegion/Templates/TestServerParameters-region2-spoke2.json


      # output containerName variable from template
    # - run: echo ${{ steps.deploy.outputs.containerName }}
