on: workflow_dispatch
name: SingleRegion-vWan-IsolatedVnetsNBranchesWithFirewall
jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
    # flag that determines if the test servers needs to be deployed to region#2
    # this helps in reusing this workflow for single and multiregion scenarios
      DEPLOYMENT_REGION: "Southeast Asia"
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    # Powershell action to complete the pre-req tasks
    # the script creates the target resource group
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
          inlineScript: 
            .\05-Singleregion-IsolatedVnetsNBranchesWithFirewall\Scripts\Prerequisite-tasks.ps1 -SubscriptionId ${{ secrets.AZURE_SUBSCRIPTION_PAYG }} -Location ${{env.DEPLOYMENT_REGION}}
        # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: latest 

    - name: Run ARM deploy for virtual Wan
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_PAYG }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./05-Singleregion-IsolatedVnetsNBranchesWithFirewall/Templates/deploySingleregionWanResources.json
        parameters: ./05-Singleregion-IsolatedVnetsNBranchesWithFirewall/Templates/deploySingleregionWanResources.Parameters.json

   
      # output containerName variable from template
    # - run: echo ${{ steps.deploy.outputs.containerName }}
